// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_FA4634FrCeLxyp99JrTsR1iJHCNRuk',
    appId: '1:1049439626401:web:89c62409d9121dca7f7ce0',
    messagingSenderId: '1049439626401',
    projectId: 'notes-f35f1',
    authDomain: 'notes-f35f1.firebaseapp.com',
    storageBucket: 'notes-f35f1.firebasestorage.app',
    measurementId: 'G-6RW07BS1NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsnjsN9wOzQybLLVUbmpJgwUmxng_F7c',
    appId: '1:1049439626401:android:8f677263126d1a027f7ce0',
    messagingSenderId: '1049439626401',
    projectId: 'notes-f35f1',
    storageBucket: 'notes-f35f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCf2xGjTBECjqvr-hC2KRp04lIEOEuBBw',
    appId: '1:1049439626401:ios:a387b5ebfc7dc6197f7ce0',
    messagingSenderId: '1049439626401',
    projectId: 'notes-f35f1',
    storageBucket: 'notes-f35f1.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCf2xGjTBECjqvr-hC2KRp04lIEOEuBBw',
    appId: '1:1049439626401:ios:a387b5ebfc7dc6197f7ce0',
    messagingSenderId: '1049439626401',
    projectId: 'notes-f35f1',
    storageBucket: 'notes-f35f1.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn_FA4634FrCeLxyp99JrTsR1iJHCNRuk',
    appId: '1:1049439626401:web:7220d009fc409b107f7ce0',
    messagingSenderId: '1049439626401',
    projectId: 'notes-f35f1',
    authDomain: 'notes-f35f1.firebaseapp.com',
    storageBucket: 'notes-f35f1.firebasestorage.app',
    measurementId: 'G-FSJZY476LV',
  );

}